# -*- mode: python ; coding: utf-8 -*-
# Generated by PyInstaller Deployment Tool
# Date: 2025-10-21 14:49:54

block_cipher = None

a = Analysis(
    ['/Users/kang/Documents/Projects/ToolsPack/dependency_analyzer.py'],
    pathex=[],
    binaries=[],
    datas=[],
    hiddenimports=[],
    hookspath=[],
    hooksconfig={},
    runtime_hooks=[],
    excludes=[],
    win_no_prefer_redirects=False,
    win_private_assemblies=False,
    cipher=block_cipher,
    noarchive=False,
)

pyz = PYZ(a.pure, a.zipped_data, cipher=block_cipher)

exe = EXE(
    pyz,
    a.scripts,
    [],
    exclude_binaries=True,
    name='dependency_analyzer',
    debug=False,
    bootloader_ignore_signals=False,
    strip=False,
    upx=False,
    console=False,
    disable_windowed_traceback=False,
    argv_emulation=False,
    target_arch=None,
    codesign_identity=None,
    entitlements_file=None,
    icon='/Users/kang/Documents/Projects/ToolsPack/r.icns',
)

coll = COLLECT(
    exe,
    a.binaries,
    a.zipfiles,
    a.datas,
    strip=False,
    upx=False,
    upx_exclude=[],
    name='dependency_analyzer',
)

app = BUNDLE(
    coll,
    name='dependency_analyzer.app',
    icon='/Users/kang/Documents/Projects/ToolsPack/r.icns' if '/Users/kang/Documents/Projects/ToolsPack/r.icns' else None,
    bundle_identifier='com.dependency_analyzer.app',
    info_plist={
        'NSHighResolutionCapable': 'True',
        'CFBundleShortVersionString': '1.0.0',
    },
)
